version: '3.8'

services:
  postgres_db:
    image:  postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!

  redis_cache:
    image:  redis:latest
    container_name: redis_bbg
    restart: always
    command: ["--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data

volumes:
  redis_cache_data:
