version: '3.8'

services:
  postgres_db:
    image:  postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!